stages:
    - deploy_prod
    
##############################################################
##PROD-master
##############################################################
build_test_portal:
    stage: deploy_prod
    only:
        - main
    resource_group: main
    variables:
        ENV_FILE_NAME: PROD_ENV
        # Костыль для копирования env в корень
        COPY_FILE_PROD_ENV: ./.env
        
        DOCKER_BUILD_APP: yotrack-plan-mindmap
        UPDATE_TAG: dev_213.18
        DOCKER_COMPOSE_FILE: docker-compose.yml
        DOCKER_COMPOSE_APP_RUN: yotrack-plan-mindmap
        DOCKER_COMPOSE_APP_STOP: yotrack-plan-mindmap
    trigger:
        strategy: depend
        include:
            -   project: 'infrastructure/infrastructure'
                ref: master
                file: 'build.gitlab-ci.yml'

    environment:
        name: 'Prod'
        url: 'https://miro-youtrack-plugin.uriit.ru/'

 
